import Foundation

struct Quote { let zh: String; let en: String }

enum Quotes {
    /// pick one quote, randomly showing its Chinese OR English line
    static func random(_ pool: [Quote]) -> String {
        let q = pool.randomElement()!
        return Bool.random() ? q.en : q.zh
    }

    static let hero: [Quote] = [
        .init(zh: "今天也辛苦了，先停一停。", en: "You've worked hard today — pause for a moment."),
        .init(zh: "此刻，只属于你自己。", en: "This moment belongs only to you."),
        .init(zh: "慢一点，没关系的。", en: "Slow down — it's okay."),
        .init(zh: "你值得被温柔对待。", en: "You deserve to be treated gently."),
        .init(zh: "给自己十秒钟的注视。", en: "Give yourself ten seconds of attention."),
        .init(zh: "不必完美，真实就好。", en: "You needn't be perfect — real is enough."),
        .init(zh: "你已经做得很好了。", en: "You're already doing well."),
        .init(zh: "深呼吸，把肩膀放松。", en: "Breathe deep, let your shoulders drop."),
        .init(zh: "今天的你，也很重要。", en: "Today's you matters too."),
        .init(zh: "把心事，轻轻放下。", en: "Set your worries down, gently."),
        .init(zh: "累了就承认累，没关系。", en: "If you're tired, admit it — that's fine."),
        .init(zh: "你从来都不是一个人。", en: "You are never in this alone."),
        .init(zh: "善待自己，从此刻开始。", en: "Be kind to yourself, starting now."),
        .init(zh: "你的感受，都算数。", en: "All your feelings count."),
        .init(zh: "停下脚步，看看自己。", en: "Pause, and look at yourself."),
        .init(zh: "今天的情绪，值得被听见。", en: "Today's feelings deserve to be heard."),
        .init(zh: "你已经很努力了，我看见了。", en: "You've tried so hard — I see it."),
        .init(zh: "允许自己，只是普通的一天。", en: "Allow yourself an ordinary day."),
        .init(zh: "温柔地，问问自己好不好。", en: "Gently ask yourself how you are."),
        .init(zh: "一天结束前，抱抱自己。", en: "Before the day ends, hug yourself."),
        .init(zh: "你不需要向谁证明什么。", en: "You owe no one any proof."),
        .init(zh: "慢慢来，时间还够。", en: "Take it slow — there's still time."),
        .init(zh: "此刻的平静，是给你的礼物。", en: "This calm is a gift for you."),
        .init(zh: "把今天，温柔地收个尾。", en: "Close today softly."),
        .init(zh: "你的存在，本身就很好。", en: "Your being here is already enough."),
        .init(zh: "感受此刻，不必急着评判。", en: "Feel this moment; don't rush to judge."),
        .init(zh: "无论今天如何，你都值得温柔。", en: "However today went, you deserve tenderness."),
        .init(zh: "给疲惫的自己，一点空间。", en: "Give your tired self some room."),
        .init(zh: "你今天，已经尽力了。", en: "You gave your best today."),
        .init(zh: "轻轻地，和今天说声谢谢。", en: "Quietly, thank today."),
        .init(zh: "别急，先照顾好情绪。", en: "No rush — tend to your feelings first."),
        .init(zh: "你比想象中更坚强。", en: "You're stronger than you think."),
        .init(zh: "这一刻，你可以只是休息。", en: "In this moment, you may simply rest."),
        .init(zh: "把好与不好，都记下来。", en: "Note it all — the good and the not."),
        .init(zh: "你愿意停下来，已经很勇敢。", en: "Pausing at all is brave."),
        .init(zh: "今晚，对自己温柔一点。", en: "Be a little gentler with yourself tonight."),
        .init(zh: "心里的声音，值得被倾听。", en: "The voice inside is worth listening to."),
        .init(zh: "不完美的一天，也是一天。", en: "An imperfect day is still a day."),
        .init(zh: "你的脚步，可以再轻一些。", en: "Let your steps be a little lighter."),
        .init(zh: "此刻，你很安全。", en: "In this moment, you are safe."),
        .init(zh: "把紧绷的自己，松开一点。", en: "Loosen the tightness in you."),
        .init(zh: "今天的星光，为你而留。", en: "Tonight's starlight is kept for you."),
        .init(zh: "你所经历的，都有意义。", en: "All you've been through means something."),
        .init(zh: "先停下，再温柔地继续。", en: "Pause first, then go on gently."),
        .init(zh: "你的好，不需要被看见才成立。", en: "Your worth doesn't need an audience."),
        .init(zh: "让心，慢慢沉静下来。", en: "Let your heart settle, slowly."),
        .init(zh: "一点点进步，也是进步。", en: "A little progress is progress."),
        .init(zh: "你已经走了很远了。", en: "You've come such a long way."),
        .init(zh: "此刻，把世界调成静音。", en: "Mute the world, just for now."),
        .init(zh: "谢谢你，今天也认真活着。", en: "Thank you for living earnestly today."),
    ]

    static let rest: [Quote] = [
        .init(zh: "你已经认真生活了一整天，现在可以放心休息了。", en: "You've lived this day fully — now you may rest."),
        .init(zh: "今天就到这里，剩下的交给明天。", en: "Let today end here; leave the rest to tomorrow."),
        .init(zh: "闭上眼睛，把一切都放下。", en: "Close your eyes and let everything go."),
        .init(zh: "你做得够多了，该休息了。", en: "You've done enough — time to rest."),
        .init(zh: "愿你今夜，睡得安稳。", en: "May you sleep soundly tonight."),
        .init(zh: "黑夜会接住所有的疲惫。", en: "The night will hold all your weariness."),
        .init(zh: "明天的事，明天再说。", en: "Tomorrow's matters can wait for tomorrow."),
        .init(zh: "此刻，你可以彻底松开。", en: "Right now, you can fully let go."),
        .init(zh: "晚安，温柔的人。", en: "Good night, gentle soul."),
        .init(zh: "把今天的重量，卸下来吧。", en: "Set down the weight of today."),
        .init(zh: "你值得一个安稳的夜晚。", en: "You deserve a peaceful night."),
        .init(zh: "月亮已经替你守夜了。", en: "The moon keeps watch for you now."),
        .init(zh: "安心睡吧，世界会等你。", en: "Sleep easy — the world will wait."),
        .init(zh: "今晚，不必再想任何事。", en: "Tonight, you needn't think of anything."),
        .init(zh: "让梦，带你去柔软的地方。", en: "Let dreams carry you somewhere soft."),
        .init(zh: "你已尽力，剩下的请交给夜。", en: "You've tried — leave the rest to the night."),
        .init(zh: "慢慢呼吸，慢慢入睡。", en: "Breathe slowly, drift slowly to sleep."),
        .init(zh: "今天辛苦了，好好睡。", en: "You worked hard today — sleep well."),
        .init(zh: "星星会替你记住今天。", en: "The stars will remember today for you."),
        .init(zh: "放下手机，拥抱困意。", en: "Put the phone down, welcome the sleepiness."),
        .init(zh: "愿温柔，伴你入眠。", en: "May tenderness see you to sleep."),
        .init(zh: "这一天，被好好收下了。", en: "This day has been gently received."),
        .init(zh: "你不必撑到最后一刻。", en: "You don't have to hold on till the very end."),
        .init(zh: "夜深了，该交给梦了。", en: "It's late — time to hand over to dreams."),
        .init(zh: "今晚的你，可以什么都不做。", en: "Tonight, you may do nothing at all."),
        .init(zh: "把烦恼，留在今天。", en: "Leave your worries in today."),
        .init(zh: "安静地，谢谢自己。", en: "Quietly, thank yourself."),
        .init(zh: "愿你被柔软的梦包围。", en: "May soft dreams surround you."),
        .init(zh: "休息，也是一种努力。", en: "Resting is its own kind of effort."),
        .init(zh: "灯灭之后，只剩温柔。", en: "After the light goes out, only gentleness remains."),
        .init(zh: "今天的句号，画得很好。", en: "You ended today just right."),
        .init(zh: "让身体，沉进床里吧。", en: "Let your body sink into the bed."),
        .init(zh: "明早醒来，又是新的一天。", en: "When you wake, it's a brand-new day."),
        .init(zh: "你已经足够好了，睡吧。", en: "You are enough — go to sleep."),
        .init(zh: "把心交给夜晚保管。", en: "Leave your heart in the night's keeping."),
        .init(zh: "愿你今夜无梦，或好梦。", en: "May tonight be dreamless, or full of good dreams."),
        .init(zh: "一切都会慢慢变好的。", en: "Everything will slowly get better."),
        .init(zh: "收下今晚的状态，晚安。", en: "Your day is logged — good night."),
        .init(zh: "现在，轮到你被照顾了。", en: "Now it's your turn to be cared for."),
        .init(zh: "闭眼前，对自己说声辛苦了。", en: "Before sleep, tell yourself: well done."),
        .init(zh: "夜很长，足够你好好歇息。", en: "The night is long enough to truly rest."),
        .init(zh: "让今天，温柔地落幕。", en: "Let today fall gently to a close."),
        .init(zh: "你好好走过了今天，真好。", en: "You walked gently through today — how lovely."),
        .init(zh: "把疲惫，泡进夜色里。", en: "Soak your tiredness in the night."),
        .init(zh: "愿好梦，轻轻找到你。", en: "May good dreams find you softly."),
        .init(zh: "现在，只需要好好睡。", en: "For now, just sleep well."),
        .init(zh: "你已经很棒了，晚安。", en: "You did great — good night."),
        .init(zh: "卸下今天，迎接安眠。", en: "Lay down today, welcome sleep."),
        .init(zh: "让呼吸，带你进入梦乡。", en: "Let your breath lead you into dreams."),
        .init(zh: "晚安，愿你被世界温柔以待。", en: "Good night — may the world be gentle with you."),
    ]
}
